### ISSUE TITLE
Implementation/Training

### ISSUE THREAD

**Issue by AsmaBaccouche** [shuuchen/HRNet#1]
Hello,

Thank you for sharing the code and I liked the post in your blog. Can you please share the implementation of the model for an image segmentation problem for example? I'm not very familiar with torch, usually I work with TensorFlow and Keras..so can you please provide an example to see how to train the model with a real dataset. Thanks!

**Comment by shuuchen** [comment]
Hi,

please refer to my another repository:
https://github.com/shuuchen/keypoint_estimation

a training file using HRNet for segmentation is:
https://github.com/shuuchen/keypoint_estimation/blob/master/train_regression.py

just prepare your own dataset and you can use it !

**Comment by AsmaBaccouche** [comment]
Thank you!
